### ISSUE TITLE
MZP and CBG files

### ISSUE THREAD

**Issue by HenDGS** [LinkOFF7/HunexFileArchiveTool#4]
Hey man, thks for ur tool!

I compiled from the source code, and it is successfully running. But I have a problem that idk how to open or what are "mzp" and "cbg" files that are extract from the .hfa. I googled and tried WinArchiver, but to no avail.

Do u guys know how can I get the assets and osts from the game?

Thanks in advance.

**Comment by LinkOFF7** [comment]
You can find out more about these files here - https://forums.nrvnqsr.com/showthread.php/9708-kuso

**Comment by LinkOFF7** [comment]
You can find out more about these files here - https://forums.nrvnqsr.com/showthread.php/9708-kuso
